#!/usr/bin/perl -w

use strict;
use warnings;

die "Usage:perl $0 <ftp>" if(@ARGV != 1);

my ( $url ) = @ARGV;

   $url  =~ s/ftp:\/\/ftp.sra.ebi.ac.uk//;
my $ftp  = qq{ascp -i /etc/asperaweb_id_dsa.openssh --overwrite=diff -QTr -l6000m -P33001  era-fasp\@fasp.sra.ebi.ac.uk:};

my $ascp = $ftp . $url . " .\n";

print  $ascp;
system $ascp;
